account/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.contrib.auth import views as auth_views

from .views import (
	login_view,
	register_view,
	logout_view,
	settings,
	change_password,
	login_redirect,
	profile,
	edit_profile,
	)

urlpatterns = [ 

	url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^settings/$', settings, name='settings'),
    url(r'^change-password/$', change_password, name='password'),
    url(r'^profile/$',profile ,name='profile'),
    url(r'^profile/edit/$',edit_profile ,name='edit_profile'),

]

gettingstarted/urls.py
from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls import include, url, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin

from account.views import login_redirect

from django.contrib import admin
admin.autodiscover()


# Examples:
# url(r'^$', 'gettingstarted.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    #workload
    url(r'^workload/', include('workload.urls', namespace='workload')),
    url(r'^thesis/', include('workload2.urls', namespace='workload2')),
    url(r'^research/', include('workload3.urls', namespace='workload3')),
    url(r'^document/', include('workload4.urls', namespace='workload4')),
    url(r'^support/', include('workload5.urls', namespace='workload5')),
    url(r'^position/', include('workload6.urls', namespace='workload6')),
    url(r'^benefit/', include('workload7.urls', namespace='workload7')),

    #account 
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^$',login_redirect,name='login_redirect'),

] 

handler404 = 'account.views.page_not_found'
handler500 = 'account.views.server_error'    

workload7/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	workload_list,
	workload_create,
	workload_update,
	workload_delete,
	workload_report,
	workload_export,
	detail,
	sum_report,
	)

urlpatterns = [ 

	url( r'^$', workload_list, name='list'),
	url( r'^create/$', workload_create,name='create'),
	url( r'^report/$', workload_report,name='report'),
	url( r'^detail/$', detail,name='detail'),
	url( r'^export/$', workload_export,name='export'),
	url( r'^(?P<id>\d+)/edit/$', workload_update, name='update'),
	url( r'^(?P<id>\d+)/delete/$', workload_delete, name='delete'),

	url( r'^api/report/$',sum_report,name='sum_report'),

]

workload7/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.timezone import now
# Create your models here.
class Benefit(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
	benefit_list = models.CharField(max_length=120)
	benefit_name = models.CharField(max_length=120)
	person_name	= models.CharField(max_length=120)
	comment = models.TextField(blank=True)
	date = models.DateTimeField(default=now)

workload7/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

# from uni_form.helper import FormHelper
from crispy_forms.helper import FormHelper

from crispy_forms.layout import Layout,Div,Submit,HTML,Button,Row,Field
from crispy_forms.bootstrap import AppendedText,PrependedText,FormActions,InlineField,StrictButton

from django.utils.timezone import datetime

from .models import Benefit

class BenefitForm(forms.ModelForm):

	user = forms.ModelChoiceField(
	        queryset=Benefit.objects.all(),
	        widget=forms.HiddenInput(),
	        required = False,
        )

	benefit_list = forms.ChoiceField(
			choices = ( 
				(u'อาจารย์ได้รับรางวัลทางวิชาการหรือวิชาชีพระดับหน่วยงานภายนอกมหาวิทยาลัย',
					'อาจารย์ได้รับรางวัลทางวิชาการหรือวิชาชีพระดับหน่วยงานภายนอกมหาวิทยาลัย'),
				(u'อาจารย์ได้รับรางวัลทางวิชาการหรือวิชาชีพระดับชาติ/นานาชาติ',
					'อาจารย์ได้รับรางวัลทางวิชาการหรือวิชาชีพระดับชาติ/นานาชาติ'),
				(u'อาจารย์ที่ปรึกษากิจกรรมการแข่งขันทางวิชาการของนักศึกษาที่ได้รับรางวัลระดับหน่วยงาน',
					'อาจารย์ที่ปรึกษากิจกรรมการแข่งขันทางวิชาการของนักศึกษาที่ได้รับรางวัลระดับหน่วยงาน'),
				(u'อาจารย์ที่ปรึกษากิจกรรมการแข่งขันทางวิชาการของนักศึกษาที่ได้รับรางวัลระดับชาติ/นานาชาติ',
					'อาจารย์ที่ปรึกษากิจกรรมการแข่งขันทางวิชาการของนักศึกษาที่ได้รับรางวัลระดับชาติ/นานาชาติ'),
				(u'อาจารย์ที่ให้ความร่วมมือในการจัดประชุมวิชาการของคณะ',
					'อาจารย์ที่ให้ความร่วมมือในการจัดประชุมวิชาการของคณะ'),
				),
			label = "รายการ",
			widget = forms.RadioSelect,
			initial = u'อาจารย์ได้รับรางวัลทางวิชาการหรือวิชาชีพระดับหน่วยงานภายนอกมหาวิทยาลัย',
			required = True,
		)

	benefit_name = forms.CharField(
			label = "ชื่อผลงาน",
			required = True,
		)

	person_name = forms.CharField(
			label = "ชื่อผู้เข้าร่วมการแข่งขัน",
			required = True,
		)

	comment = forms.CharField(
			label = "หมายเหตุ",
			widget = forms.Textarea(),
			required = False,
		)

	def __init__(self, *args, **kwargs):

		super(BenefitForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.label_class = 'col-md-3 col-md-offset-1'
		self.helper.field_class = 'col-md-5'
		self.helper.layout = Layout(

				Field('benefit_list'),
				Field('benefit_name',),
				Field('person_name'),
				Field('comment',),
				Div(
					Submit('submit','Submit'),
					style='text-align:center;'
					)
		)

	class Meta:
		model = Benefit
		fields = [
						"benefit_list",
						"benefit_name",
						"person_name",
						"comment",
			]	

		

class ChosenForm(forms.ModelForm):
	YEAR_CHOICES = []
 	for r  in range(2016,(datetime.today().year)+1):
 		YEAR_CHOICES.append((r,r))

 	year = forms.ChoiceField(
			choices = YEAR_CHOICES,
			initial=datetime.today().year,
			)

	def __init__(self, *args, **kwargs):

		super(ChosenForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.field_template = 'bootstrap3/layout/inline_field.html' 
		self.helper.form_class = 'form-inline'
		self.helper.form_id = 'chosen_sub'
		self.helper.layout = Layout(

				'year',
					Submit('submit','Submit'),
		)

	class Meta:
		model = Benefit
		fields = [
					"year",
				]

workload7/views.py
#-*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from django.db.models import Count,Sum
from .excel_utils import WriteToExcel,WriteToExcelManager

from django.utils.timezone import datetime

from .models import Benefit
from .forms import BenefitForm,ChosenForm

# Create your views here.
@login_required
def workload_list(request,id=None):
	current_user = request.user
	if request.user.is_staff or request.user.is_superuser:
		return redirect("workload7:report")
	else:
		queryset = Benefit.objects.filter(user=current_user,date__year=datetime.today().year)
		if request.method == "POST":
			form = ChosenForm(request.POST or None)
			date = request.POST.get("year")
			queryset = Benefit.objects.filter(user=current_user,date__year=date)
		else:
			form = ChosenForm()
	
	context = {
		"form": form,
		"object_list": queryset,
		"current_user":current_user,
	}
	return render(request,"workload7/workload_list.html",context)

	
@login_required
def workload_create(request):
	current_user = request.user
	if request.method == "POST":
		form = BenefitForm(request.POST or None, initial={'user':current_user,})
		if form.is_valid():
			print("success")
			instance = form.save(commit=False)
			instance.user = current_user
			instance.save()
			messages.success(request,"Successfully Created")
			return redirect("workload7:list")
		else:
			print(form)
			messages.error(request, "Not Successfully Created")

	else:
		form = BenefitForm()

	context = {
		"head" : u"แบบฟอร์มรางวัลต่างๆ",
		"form": form,
		"current_user":current_user,
	}
	return render(request, "workload_form.html", context)


@login_required
def workload_update(request, id=None):
	instance = get_object_or_404(Benefit,id=id)
	form = BenefitForm(request.POST or None, instance=instance)
	print(form.errors)

	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = instance.user
		instance.save()
		messages.success(request,"<a href='#'>Saved</a>",extra_tags='html_safe')
		return redirect("workload7:list")
	
	else:
		print("2")

	context = {
		"head" : u"แก้ไขแบบฟอร์มรางวัลต่างๆ",
		"form": form,
		"instance" : instance,
		"current_user":request.user,
	}
	return render(request, "workload_form.html", context)

	
@login_required
def workload_delete(request, id=None):
	instance = get_object_or_404(Benefit,id=id)
	instance.delete()
	messages.success(request,"Successfully Deleted")
	return redirect("workload7:list")


@login_required
def workload_export(request, id=None):
	current_user = request.user
	response = HttpResponse(content_type='application/vnd.ms-excel')
	response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
	if request.user.is_staff or request.user.is_superuser:
		queryset = Benefit.objects.all().filter(date__year=datetime.today().year)
		xlsx_data = WriteToExcelManager(queryset,current_user)
		response.write(xlsx_data)
	else:
		queryset = Benefit.objects.filter(user=current_user,date__year=datetime.today().year)
		xlsx_data = WriteToExcel(queryset,current_user)
		response.write(xlsx_data)

	return response


@login_required
def workload_report(request):
	current_user = request.user
	if not request.user.is_staff:
		return redirect("404.html")
	else:
		if request.method == "POST":
			form = ChosenForm(request.POST or None)
			date = request.POST.get("year")
		else:
			form = ChosenForm()

	context ={
		# "year" : year ,
		"form" : form,
		"current_user":current_user,
	}
	return render(request, "workload7/workload_report.html",context)


@login_required
def detail(request):
	return render(request, "workload7/detail.html")


@login_required
def sum_report(request):
	data = Benefit.objects.all().values('user__username').annotate(total=Count('user'))
	for instance in data:
		print(instance)

	return JsonResponse(list(data), safe=False)

templates/workload7/detail.html
{% extends "base.html" %}

{% load staticfiles %}


{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}


<h1>Teacher1</h1>

<svg width="300" height="400"></svg>
<script>
	

	var svg = d3.select("svg"),
	    margin = {top: 20, right: 20, bottom: 30, left: 40},
	    width = +svg.attr("width") - margin.left - margin.right,
	    height = +svg.attr("height") - margin.top - margin.bottom;

	var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
	    y = d3.scaleLinear().rangeRound([height, 0]);

	var g = svg.append("g")
	    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

	d3.csv("{% static 'mydata.csv' %}", function(d) {
	  d.age = +d.age;
	  return d;
	}, function(error, data) {
	  if (error) throw error;

	  x.domain(data.map(function(d) { return d.name; }));
	  y.domain([0, d3.max(data, function(d) { return d.age; })]);

	  g.append("g")
	      .attr("class", "axis axis--x")
	      .attr("transform", "translate(0," + height + ")")
	      .call(d3.axisBottom(x));

	  g.append("g")
	      .attr("class", "axis axis--y")
	      .call(d3.axisLeft(y))
	    .append("text")
	      .attr("transform", "rotate(-90)")
	      .attr("y", 6)
	      .attr("dy", "0.71em")
	      .attr("text-anchor", "end")
	      .text("Frequency");

	  g.selectAll(".bar")
	    .data(data)
	    .enter().append("rect")
	      .attr("class", "bar")
	      .attr("x", function(d) { return x(d.name); })
	      .attr("y", function(d) { return y(d.age); })
	      .attr("width", x.bandwidth())
	      .attr("height", function(d) { return height - y(d.age); });
	});
</script>


 

{% endblock content%}

templates/workload7/workload_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% crispy TeachingForm TeachingForm.helper %}


{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  <div class="row">
		<div class="col-lg-12">
	  		<h3 class="page-header">รางวัลต่างๆ</h3>
	  	</div>
	</div>
  	<div class="row">
	  	<div class="col-lg-6">
			{% csrf_token %}
			{% crispy form %}
		</div>
	  	<div class="col-lg-6 ">
	  		<a href="{% url 'workload7:create' %}" class="btn btn-default pull-right">เพิ่ม</a>
	  		<!-- <a class="glyphicon glyphicon-plus btn btn-info" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" ></a> -->
		</div>
	</div>
	<br>
	<div class="row">
	<div class="col-lg-12">
	<table class="table table-hover" >
		<thead>
			<tr>
				<th class="col-lg-4 text-center">รายการ</th>
				<th class="col-lg-3 text-center">ชื่อผลงาน</th>
				<th class="text-center">ชื่อผู้เข้าร่วมการแข่งขัน</th>
				<th class="text-center"></th>
				{% if request.user.is_staff  %}
				<th class="text-center">User</th>
				{% endif %}
				<th class="text-center"></th>
				<th class="text-center"></th>
			</tr>
		</thead>
		<tbody>
			{% for obj in object_list %}	
			<tr>
				<td class="text-center">{{ obj.benefit_list }}</td>
				<td class="text-center">{{ obj.benefit_name }}</td>
				<td class="text-center">{{ obj.person_name }}</td>
				<td class="text-center">
						{% if obj.comment %}
						<a href="">
							<span class="glyphicon glyphicon-comment" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="{{obj.comment}}"></span></a>
						{% else %}
						<p class="text-center"><small></small></p>
						{% endif %}
				</td>
				{% if request.user.is_staff  %}
				<td class="text-center">{{ obj.user}}</td>
				{% endif %}
				<td class="text-center">
					<a class="glyphicon glyphicon-cog" href="{% url 'workload7:update' id=obj.id %}">
					</a>
				</td>
				<td class="text-center">
					<a href="{% url 'workload7:delete' id=obj.id %}" >
						<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
					</a>
				</td>
			</tr>
			{% endfor%}
		</tbody>
	</table>
	</div>
	</div>
	

	<!-- workload form -->
	<!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
		<div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="exampleModalLabel">Form</h4>
		      </div>
		      <div class="modal-body">

		      </div>
		    </div>
		</div>
	</div> -->

{% endblock content%}

templates/workload7/workload_report.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">รายงานของรางวัลต่างๆ</h3>
	</div>
</div>

<div class="row">
    <div class="col-lg-6 ">
        <p>จำนวนรางวัลของอาจารย์แต่ละท่าน ปี {{year}}</p>
    </div>
    <div class="col-lg-6">
            {% csrf_token %}
            {% crispy form %}
    </div>
</div>
<br>
<div class="row">
	<div class="col-lg-12">
		<div id="svg"></div>
	</div>
</div>
<script src="//d3js.org/d3.v4.min.js"></script>
<script>

// set the dimensions and margins of the graph
var margin = {top: 20, right: 20, bottom: 30, left: 40},
    width = 560- margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

var c10 = d3.scaleOrdinal(d3.schemeCategory10);

// set the ranges
var x = d3.scaleBand()
          .range([0, width])
          .padding(0.1);
var y = d3.scaleLinear()
          .range([height, 0]);
          
// append the svg object to the body of the page
// append a 'group' element to 'svg'
// moves the 'group' element to the top left margin
var svg = d3.select("#svg").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", 
          "translate(" + margin.left + "," + margin.top + ")");

// get the data
var url = "{% url 'workload7:sum_report' %}";
d3.json(url, function(error, data) {
    if (error) throw error;

    // format the data
    data.forEach(function(d) {
    d.total = +d.total;
     });

    // Scale the range of the data in the domains
    x.domain(data.map(function(d) { return d.user__username; }));
    y.domain([0, d3.max(data, function(d) { return d.total; })]);

    // append the rectangles for the bar chart
    svg.selectAll(".bar")
        .data(data)
        .enter().append("rect")
        .attr("class", "bar")
        .attr("x", function(d) { return x(d.user__username); })
        .attr("width", x.bandwidth())
        .attr("y", function(d) { return y(d.total); })
        .attr("height", function(d) { return height - y(d.total); })
        .attr("fill",function(d) {return c10(d.user__username);});

    // add the x Axis
    svg.append("g")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(x));

    // add the y Axis
    svg.append("g")
        .call(d3.axisLeft(y)
            .tickFormat(d3.format("d"))
            .ticks(d3.max(data, function(d) { return d.total; }))
            );
    });

</script>

 

{% endblock content%}