account/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.contrib.auth import views as auth_views

from .views import (
	login_view,
	register_view,
	logout_view,
	settings,
	change_password,
	login_redirect,
	profile,
	edit_profile,
	)

urlpatterns = [ 

	url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^settings/$', settings, name='settings'),
    url(r'^change-password/$', change_password, name='password'),
    url(r'^profile/$',profile ,name='profile'),
    url(r'^profile/edit/$',edit_profile ,name='edit_profile'),

]

gettingstarted/urls.py
from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls import include, url, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin

from account.views import login_redirect

from django.contrib import admin
admin.autodiscover()


# Examples:
# url(r'^$', 'gettingstarted.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    #workload
    url(r'^workload/', include('workload.urls', namespace='workload')),
    url(r'^thesis/', include('workload2.urls', namespace='workload2')),
    url(r'^research/', include('workload3.urls', namespace='workload3')),
    url(r'^document/', include('workload4.urls', namespace='workload4')),
    url(r'^support/', include('workload5.urls', namespace='workload5')),
    url(r'^position/', include('workload6.urls', namespace='workload6')),
    url(r'^benefit/', include('workload7.urls', namespace='workload7')),

    #account 
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^$',login_redirect,name='login_redirect'),

] 

handler404 = 'account.views.page_not_found'
handler500 = 'account.views.server_error'    

workload/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	workload_list,
	workload_create,
	workload_update,
	workload_delete,
	workload_report,
	# workload_export,
	# workload_export_score,
	workload_ex,
	workload_ex2,
	detail,
	sum_report,
	)

urlpatterns = [ 

	url( r'^$', workload_list, name='list'),
	url( r'^create/$', workload_create,name='create'),
	url( r'^report/$', workload_report,name='report'),
	url( r'^detail/$', detail,name='detail'),
	# url( r'^export/$', workload_export,name='export'),
	# url( r'^exportscore/$', workload_export_score,name='exportscore'),
	url( r'^export/$',workload_ex,name='export'),
	url( r'^exportscore/$',workload_ex2,name='exportscore'),
	url( r'^(?P<id>\d+)/edit/$', workload_update, name='update'),
	url( r'^(?P<id>\d+)/delete/$', workload_delete, name='delete'),

	url( r'^api/report/$',sum_report,name='sum_report'),

]

workload/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.timezone import now,datetime



class Teaching(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
	subject_ID = models.CharField(max_length=10)
	subject = models.CharField(max_length=120)
	ratio = models.IntegerField()
	num_of_lecture = models.IntegerField()
	num_of_lab = models.IntegerField()
	program_ID = models.CharField(max_length=120)
	# program_ID = models.ForeignKey(Program)
	num_of_student = models.IntegerField()
	comment = models.TextField(blank=True)
	date = models.DateTimeField(default=now,editable=True)

workload/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

# from uni_form.helper import FormHelper
from crispy_forms.helper import FormHelper

from crispy_forms.layout import Layout,Div,Submit,HTML,Button,Row,Field
from crispy_forms.bootstrap import AppendedText,PrependedText,FormActions,InlineField,StrictButton,FieldWithButtons

from django.utils.timezone import datetime

from .models import Teaching

class TeachingForm(forms.ModelForm):

	user = forms.ModelChoiceField(
	        queryset=Teaching.objects.all(),
	        widget=forms.HiddenInput(),
	        required = False,
        )

	# date = forms.DateField(
	# 		label = "วันที่",
	# 		widget=forms.SelectDateWidget,
	# 		initial = datetime.date.today,
	# 		required = False,

	# 	)

	subject_ID = forms.CharField(
			label = "รหัสวิชา",
			required = True,
		)

	subject = forms.CharField(
			label = "ชื่อวิชา",
			required = True,
		)

	ratio = forms.IntegerField(
			label = "สัดส่วนการสอน(คิดเป็นร้อยละ)",
			required = True,
		)

	num_of_lecture = forms.IntegerField(
			label = "จำนวนหน่วยกิตการบรรยาย",
			required = True,
		)

	num_of_lab = forms.IntegerField(
			label = "จำนวนหน่วยกิตการปฏิบัติการ",
			required = True,
		)

	# program_ID = forms.ModelChoiceField(
	#         queryset=Program.objects.all(),
	#         required = True,
	#         label = "ประเภทโครงการ",
	# 		widget = forms.RadioSelect,
	# 		initial = u'โครงการปกติ',

 #        )

	program_ID = forms.ChoiceField(
			choices = ( 
				(u'โครงการปกติ','โครงการปกติ'),
				(u'โครงการพิเศษได้ค่าตอบแทน','โครงการพิเศษได้ค่าตอบแทน'),
				(u'โครงการพิเศษไม่ได้ค่าตอบแทน','โครงการพิเศษไม่ได้ค่าตอบแทน'),
				(u'งานสอนคณะอื่นภายใน มธ. ที่ไม่ได้ค่าตอบแทน','งานสอนคณะอื่นภายใน มธ. ที่ไม่ได้ค่าตอบแทน'),
				),
			label = "ประเภทโครงการ",
			widget = forms.RadioSelect,
			initial = u'โครงการปกติ',
			required = True,
		)

	num_of_student = forms.IntegerField(
			label = "จำนวนนักศึกษา",
			required = True,
		)

	comment = forms.CharField(
			label = "หมายเหตุ",
			widget = forms.Textarea(),
			required = False,
		)

	def __init__(self, *args, **kwargs):

		super(TeachingForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.label_class = 'col-md-3 col-md-offset-1'
		self.helper.field_class = 'col-md-5'
		self.helper.form_id = 'teaching_sub'
		# self.fields['program_ID'].queryset = Program.objects.all()
		self.helper.layout = Layout(

				Field('subject_ID'),
				Field('subject'),
				Field('ratio',),
				Field('num_of_lecture',),
				Field('num_of_lab',),
				Field('program_ID',),
				Field('num_of_student',),
				Field('comment',),
				FormActions(
					Submit('submit','Submit'),
					Button('cancel','Cancel' ,css_class='btn-default')
					
					)
		)

	class Meta:
		model = Teaching
		fields = [
						"subject_ID",
						"subject",
						"ratio",
						"num_of_lecture",
						"num_of_lab",
						"program_ID",
						"num_of_student",
						"comment",
			]


class ChosenForm(forms.ModelForm):

 	YEAR_CHOICES = []
 	for r  in range(2016,(datetime.today().year)+1):
 		YEAR_CHOICES.append((r,r))

 	year = forms.ChoiceField(
			choices = YEAR_CHOICES,
			initial=datetime.today().year,
			)
 	
	def __init__(self, *args, **kwargs):

		super(ChosenForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.field_template = 'bootstrap3/layout/inline_field.html' 
		self.helper.form_class = 'form-inline'
		self.helper.form_id = 'chosen_sub'
		self.helper.layout = Layout(

				'year',
				Submit('submit','Submit'),
		)

	class Meta:
		model = Teaching
		fields = [
					"year",
				]

workload/views.py
#-*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from django.db.models import Count,Sum
from .excel_utils import WriteToExcelAll

from django.utils.timezone import datetime

from .models import Teaching
from workload2.models import Thesis
from workload3.models import Research
from workload4.models import Document
from workload5.models import Support
from workload6.models import Position
from workload7.models import Benefit

from .forms import TeachingForm ,ChosenForm

# Create your views here.
@login_required
def workload_list(request,id=None):

	current_user = request.user
	if request.user.is_staff or request.user.is_superuser:
		return redirect("workload:report")

	else:
		queryset = Teaching.objects.filter(user=current_user,date__year=datetime.today().year)
		if request.method == "POST":
			form = ChosenForm(request.POST or None)
			date = request.POST.get("year")
			queryset = Teaching.objects.filter(user=current_user,date__year=date)
		else:
			form = ChosenForm()
	
	context = {
		# "form": form,
		"form" : form,
		"object_list": queryset,
		"current_user":current_user,
	}
	return render(request,"workload/workload_list.html",context)

	
@login_required
def workload_create(request):
	current_user = request.user
	if request.method == "POST":
		form = TeachingForm(request.POST or None, initial={'user':current_user,})
		if form.is_valid():
			print("success")
			instance = form.save(commit=False)
			instance.user = current_user
			instance.save()
			messages.success(request,"Successfully Created")
			return redirect("workload:list")
		else:
			messages.error(request, "Not Successfully Created")
	else:
		form = TeachingForm()

	context = {
		"head" : u"แบบฟอร์มงานสอน",
		"form": form,
		"current_user":current_user,
	}
	return render(request, "workload_form.html", context)


@login_required
def workload_update(request, id=None):
	instance = get_object_or_404(Teaching,id=id)
	form = TeachingForm(request.POST or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = instance.user
		instance.save()
		messages.success(request,"<a href='#'>Saved</a>",extra_tags='html_safe')
		return redirect("workload:list")
	else:
		print("2")

	context = {
		"current_user":request.user,
		"head" : u"แก้ไขแบบฟอร์มงานสอน",
		"form": form,
		"instance" : instance,
	}
	return render(request, "workload_form.html", context)

	
@login_required
def workload_delete(request, id=None):
	instance = get_object_or_404(Teaching,id=id)
	instance.delete()
	messages.success(request,"Successfully Deleted")
	return redirect("workload:list")

@login_required
def workload_ex(request):
	current_user = request.user
	if request.method == "POST":
		form = ChosenForm(request.POST or None)
		date = request.POST.get("year")

		response = HttpResponse(content_type='application/vnd.ms-excel')
		response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
		if request.user.is_staff or request.user.is_superuser:
			queryset = Teaching.objects.all().filter(date__year=date)
			queryset2 = Thesis.objects.all().filter(date__year=date)
			queryset3 = Research.objects.all().filter(date__year=date)
			queryset4 = Document.objects.all().filter(date__year=date)
			queryset5 = Support.objects.all().filter(date__year=date)
			queryset6 = Position.objects.all().filter(date__year=date)
			queryset7 = Benefit.objects.all().filter(date__year=date)
			xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,0,1)
			response.write(xlsx_data)
		else:
			queryset = Teaching.objects.filter(user=current_user,date__year=date)
			queryset2 = Thesis.objects.filter(user=current_user,date__year=date)
			queryset3 = Research.objects.filter(user=current_user,date__year=date)
			queryset4 = Document.objects.filter(user=current_user,date__year=date)
			queryset5 = Support.objects.filter(user=current_user,date__year=date)
			queryset6 = Position.objects.filter(user=current_user,date__year=date)
			queryset7 = Benefit.objects.filter(user=current_user,date__year=date)
			xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,0,0)
			response.write(xlsx_data)
		return response

	else:
		form = ChosenForm()
	
	context = {
		# "form": form,
		"form" : form,
		"current_user":current_user,
	}
	return render(request,"chosen_report.html",context)


@login_required
def workload_ex2(request):
	current_user = request.user
	if request.method == "POST":
		form = ChosenForm(request.POST or None)
		date = request.POST.get("year")

		response = HttpResponse(content_type='application/vnd.ms-excel')
		response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
		if request.user.is_staff or request.user.is_superuser:
			queryset = Teaching.objects.all().filter(date__year=date)
			queryset2 = Thesis.objects.all().filter(date__year=date)
			queryset3 = Research.objects.all().filter(date__year=date)
			queryset4 = Document.objects.all().filter(date__year=date)
			queryset5 = Support.objects.all().filter(date__year=date)
			queryset6 = Position.objects.all().filter(date__year=date)
			queryset7 = Benefit.objects.all().filter(date__year=date)
			xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,1,1)
			response.write(xlsx_data)
		else:
			queryset = Teaching.objects.filter(user=current_user,date__year=date)
			queryset2 = Thesis.objects.filter(user=current_user,date__year=date)
			queryset3 = Research.objects.filter(user=current_user,date__year=date)
			queryset4 = Document.objects.filter(user=current_user,date__year=date)
			queryset5 = Support.objects.filter(user=current_user,date__year=date)
			queryset6 = Position.objects.filter(user=current_user,date__year=date)
			queryset7 = Benefit.objects.filter(user=current_user,date__year=date)
			xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,1,0)
			response.write(xlsx_data)

		return response

	else:
		form = ChosenForm()
	
	context = {
		# "form": form,
		"form" : form,
		"current_user":current_user,
	}
	return render(request,"chosen_report.html",context)



# @login_required
# def workload_export(request):
# 	current_user = request.user
# 	response = HttpResponse(content_type='application/vnd.ms-excel')
# 	response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
# 	if request.user.is_staff or request.user.is_superuser:
# 		queryset = Teaching.objects.all().filter(date__year=datetime.today().year)
# 		queryset2 = Thesis.objects.all().filter(date__year=datetime.today().year)
# 		queryset3 = Research.objects.all().filter(date__year=datetime.today().year)
# 		queryset4 = Document.objects.all().filter(date__year=datetime.today().year)
# 		queryset5 = Support.objects.all().filter(date__year=datetime.today().year)
# 		queryset6 = Position.objects.all().filter(date__year=datetime.today().year)
# 		queryset7 = Benefit.objects.all().filter(date__year=datetime.today().year)
# 		xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,0,1)
# 		response.write(xlsx_data)
# 	else:
# 		queryset = Teaching.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset2 = Thesis.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset3 = Research.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset4 = Document.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset5 = Support.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset6 = Position.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset7 = Benefit.objects.filter(user=current_user,date__year=datetime.today().year)
# 		xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,0,0)
# 		response.write(xlsx_data)

# 	return response


# @login_required
# def workload_export_score(request):
# 	current_user = request.user
# 	response = HttpResponse(content_type='application/vnd.ms-excel')
# 	response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
# 	if request.user.is_staff or request.user.is_superuser:
# 		queryset = Teaching.objects.all().filter(date__year=datetime.today().year)
# 		queryset2 = Thesis.objects.all().filter(date__year=datetime.today().year)
# 		queryset3 = Research.objects.all().filter(date__year=datetime.today().year)
# 		queryset4 = Document.objects.all().filter(date__year=datetime.today().year)
# 		queryset5 = Support.objects.all().filter(date__year=datetime.today().year)
# 		queryset6 = Position.objects.all().filter(date__year=datetime.today().year)
# 		queryset7 = Benefit.objects.all().filter(date__year=datetime.today().year)
# 		xlsx_data = WriteToExcelAll(queryset,queryset2,queryset3,queryset4,queryset5,queryset6,queryset7,current_user,1,1)
# 		response.write(xlsx_data)
# 	else:
# 		queryset = Teaching.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset2 = Thesis.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset3 = Research.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset4 = Document.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset5 = Support.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset6 = Position.objects.filter(user=current_user,date__year=datetime.today().year)
# 		queryset7 = Benefit.objects.filter(user=current_user,date__year=datetime.today().year)

templates/workload/detail.html
{% extends "base.html" %}

{% load staticfiles %}


{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}


<h1>Teacher1</h1>

<svg width="300" height="400"></svg>
<script>
	

	var svg = d3.select("svg"),
	    margin = {top: 20, right: 20, bottom: 30, left: 40},
	    width = +svg.attr("width") - margin.left - margin.right,
	    height = +svg.attr("height") - margin.top - margin.bottom;

	var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
	    y = d3.scaleLinear().rangeRound([height, 0]);

	var g = svg.append("g")
	    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

	d3.csv("{% static 'mydata.csv' %}", function(d) {
	  d.age = +d.age;
	  return d;
	}, function(error, data) {
	  if (error) throw error;

	  x.domain(data.map(function(d) { return d.name; }));
	  y.domain([0, d3.max(data, function(d) { return d.age; })]);

	  g.append("g")
	      .attr("class", "axis axis--x")
	      .attr("transform", "translate(0," + height + ")")
	      .call(d3.axisBottom(x));

	  g.append("g")
	      .attr("class", "axis axis--y")
	      .call(d3.axisLeft(y))
	    .append("text")
	      .attr("transform", "rotate(-90)")
	      .attr("y", 6)
	      .attr("dy", "0.71em")
	      .attr("text-anchor", "end")
	      .text("Frequency");

	  g.selectAll(".bar")
	    .data(data)
	    .enter().append("rect")
	      .attr("class", "bar")
	      .attr("x", function(d) { return x(d.name); })
	      .attr("y", function(d) { return y(d.age); })
	      .attr("width", x.bandwidth())
	      .attr("height", function(d) { return height - y(d.age); });
	});
</script>


 

{% endblock content%}

templates/workload/workload_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% crispy TeachingForm TeachingForm.helper %}
{% crispy ChosenForm ChosenForm.helper %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
	<div class="row">
		<div class="col-lg-12">
	  		<h3 class="page-header">งานสอน</h3>
	  	</div>
	</div>
  	<div class="row">
  		<div class="col-lg-6">
			{% csrf_token %}
			{% crispy form %}
		</div>
	  	<div class="col-lg-6 ">
	  		<a href="{% url 'workload:create' %}" class="btn btn-default pull-right">เพิ่ม</a>
	  		<!-- <a class="glyphicon glyphicon-plus btn btn-info" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" ></a> -->
		</div>
	</div>
	<br>
	
	<br>
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-hover" >
				<thead>
					<tr>
						<th class="text-center">รหัสวิชา</th>
						<th class="text-center">ชื่อวิชา</th>
						<th class="text-center">สัดส่วนการสอน</th>
						<th class="text-center"><div><span>จำนวนหน่วยกิตการบรรยาย</div></span></th>
						<th class="text-center">จำนวนหน่วยกิตการปฏิบัติการ</th>
						<th class="text-center">ประเภทโครงการ</th>
						<th class="text-center">จำนวนนักศึกษา</th>
						<th class="text-center"></th>
						{% if request.user.is_staff  %}
						<th class="text-center">User</th>
						{% endif %}
						<th class="text-center"></th>
						<th class="text-center"></th>
					</tr>
				</thead>
				<tbody>
					{% for obj in object_list %}	
					<tr>
						<td class="text-center">{{ obj.subject_ID }}</td>
						<td class="text-center">{{ obj.subject }}</td>
						<td class="text-center">{{ obj.ratio }}</td>
						<td class="text-center">{{ obj.num_of_lecture }}</td>
						<td class="text-center">{{ obj.num_of_lab }}</td>
						<td class="text-center"><small>{{ obj.program_ID }}</small></td>
						<td class="text-center">{{ obj.num_of_student }}</td>
						<td class="text-center">
								{% if obj.comment %}
								<a href="">
									<span class="glyphicon glyphicon-comment" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="{{obj.comment}}"></span></a>
								{% else %}
								<p class="text-center"><small></small></p>
								{% endif %}
						</td>
						{% if request.user.is_staff  %}
						<td class="text-center">{{ obj.user}}</td>
						{% endif %}
						<td class="text-center">
							<a href="{% url 'workload:update' id=obj.id %}">
								<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
							</a>
						</td>
						<td class="text-center">
							<a href="{% url 'workload:delete' id=obj.id %}">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</a>
						</td>
					</tr>
					{% endfor%}
				</tbody>
			</table>
		</div>
	</div>
{% endblock content%}

templates/workload/workload_report.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% crispy ChosenForm ChosenForm.helper %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header">รายงานของงานสอน</h3>
	</div>
</div>

<div class="row">
    <div class="col-lg-6 ">
        <p>จำนวนหน่วยกิตที่บรรยายต่อสัปดาห์ ปี {{year}}</p>
    </div>
    <div class="col-lg-6">
            {% csrf_token %}
            {% crispy form %}
    </div>
</div>
<br>


<div class="row">
	<div class="col-lg-12">
		<div id="svg"></div>
	</div>
</div>

<script src="//d3js.org/d3.v4.min.js"></script>
<script>

// set the dimensions and margins of the graph
var margin = {top: 20, right: 20, bottom: 30, left: 40},
    width = 560 - margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

var c10 = d3.scaleOrdinal(d3.schemeCategory10);

// set the ranges
var x = d3.scaleBand()
          .range([0, width])
          .padding(0.1);
var y = d3.scaleLinear()
          .range([height, 0]);
          
// append the svg object to the body of the page
// append a 'group' element to 'svg'
// moves the 'group' element to the top left margin
var svg = d3.select("#svg").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", 
          "translate(" + margin.left + "," + margin.top + ")");

// get the data
var url = "{% url 'workload:sum_report' %}";
d3.json(url, function(error, data) {
    if (error) throw error;

    // format the data
    data.forEach(function(d) {
      d.sum_items = +d.sum_items;
    });

    // Scale the range of the data in the domains
    x.domain(data.map(function(d) { return d.user__username; }));
    y.domain([0, d3.max(data, function(d) { return d.sum_items; })]);

     // append the rectangles for the bar chart
     svg.selectAll(".bar")
        .data(data)
        .enter().append("rect")
        .attr("class", "bar")
        .attr("x", function(d) { return x(d.user__username); })
        .attr("width", x.bandwidth())
        .attr("y", function(d) { return y(d.sum_items); })
        .attr("height", function(d) { return height - y(d.sum_items); })
        .attr("fill",function(d) {return c10(d.user__username);});

    // add the x Axis
    svg.append("g")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(x));

    // add the y Axis
    svg.append("g")
        .call(d3.axisLeft(y)
            .tickFormat(d3.format("d"))
            .ticks(d3.max(data, function(d) { return d.sum_items; }))
            );

    svg.append("text")
        .attr("x",function(d) {return x(d.user__username);})
        .attr("y",function(d) {return y(d.sum_items);})
        .attr("dy","20px")
        .attr("dx",function(d){return x(d.user__username)/2;})
        .attr("fill","#fff")
        .attr("text-anchor",middle)
        .text(function(d) {return d.sum_items;});


        



    });

</script>

{% endblock content%}